### ISSUE TITLE
Use of Visualize

### ISSUE THREAD

**Issue by dpieski** [jstockwin/py-pdf-parser#122]
**Bug Report**

Please also check that your bug is not actually caused by [pdfminer.six](https://github.com/pdfminer/pdfminer.six), and is really an issue with this project.

example:
```python
from py_pdf_parser.loaders import load_file
from py_pdf_parser.visualise import visualise

document = load_file("1907-1912_RESULTS.pdf")
visualise(document)
```
Error:
```bash
Traceback (most recent call last):
  File "C:\Users\andrewp\AppData\Roaming\Python\Python38\site-packages\wand\api.py", line 180, in <module>
    libraries = load_library()
  File "C:\Users\andrewp\AppData\Roaming\Python\Python38\site-packages\wand\api.py", line 135, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: [~/CORE_RL_wand_.dll, etc.]
```

Problem: imagemagic v7+ no longer includes the searched-for dll files.

Resolution: 
Uninstall most recent imagemagic (7.0.10-34) and install the latest legacy imagemagic (6.9.11-34)

Solution: 
Provide compatibility with v7+ or note that one should install the Legacy version.

**Comment by jstockwin** [comment]
Hey @dpieski

Thanks for submitting the issue.

Could you please confirm if this works for you with v7+ when following these instructions to download the DLL files?
https://docs.wand-py.org/en/0.4.1/guide/install.html#install-imagemagick-on-windows

If so, I think this is a documentation issue, and will link to those install instructions somewhere in the docs. Sound good?

**Comment by jstockwin** [comment]
Closing due to inactivity. Please do re-open if you have this issue still and if you've checked the above.
